<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <UseWindowsForms>False</UseWindowsForms>
    <ApplicationIcon>Assets\fiz.ico</ApplicationIcon>
    <StartupObject>src.App</StartupObject>
    <AssemblyName>Fiz</AssemblyName>
    <Platforms>AnyCPU;x64</Platforms>
    <PublishSingleFile>true</PublishSingleFile>
    <IncludeNativeLibrariesForSelfExtract>true</IncludeNativeLibrariesForSelfExtract>
    <EnableCompressionInSingleFile>true</EnableCompressionInSingleFile>
    <Copyright>Copyright 2022 Joseph Cassman</Copyright>
    <PackageProjectUrl>https://github.com/josephcassman/fiz</PackageProjectUrl>
    <RepositoryUrl>https://github.com/josephcassman/fiz</RepositoryUrl>
    <VersionPrefix>$(AssemblyVersion)</VersionPrefix>
    <AssemblyVersion>0.8</AssemblyVersion>
    <FileVersion>$(AssemblyVersion)</FileVersion>
    <Version>$(AssemblyVersion)</Version>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <RepositoryType>git</RepositoryType>
    <PackageTags>media viewer</PackageTags>
    <PackageIcon>fiz.png</PackageIcon>
    <Description>A simple media viewer</Description>
    <Title>Fiz</Title>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="UI.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.4191.47" />
  </ItemGroup>

  <ItemGroup>
    <None Remove="fiz.png" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\fiz.ico" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\..\assets\fiz.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\LICENSE">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

  <ItemGroup>
    <SplashScreen Include="Assets\fiz.png" />
  </ItemGroup>

</Project>
